"""Skill promotion: cluster recurring memories into Claude Code SKILL.md files.

Algorithm (greedy cosine clustering):
  1. Load memories with kind in PROMOTABLE_KINDS that are not already promoted.
  2. Sort by (use_count DESC, confidence DESC) — strongest first.
  3. For each ungrouped memory, seed a cluster; pull in any other ungrouped
     memory whose cosine similarity to the seed is >= SIM_THRESHOLD.
  4. Filter to clusters with >= min_cluster members spanning >= min_sessions
     distinct source_session_ids.
  5. Scope: project if all members share one source_cwd; else global.
  6. Write `<scope>/skills/proposed-<slug>/SKILL.md`. Never overwrite — append
     -2, -3 if a draft already exists. Mark contributing memories as promoted.
"""
from __future__ import annotations

import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from . import store

_log = store.get_logger("agentic-brain.skills")


PROMOTABLE_KINDS = {"code-pattern", "preference", "decision"}
SIM_THRESHOLD = float(os.environ.get("AGENTIC_BRAIN_SKILL_SIM", "0.50"))
DEFAULT_MIN_CLUSTER = int(os.environ.get("AGENTIC_BRAIN_SKILL_MIN_CLUSTER", "3"))
DEFAULT_MIN_SESSIONS = int(os.environ.get("AGENTIC_BRAIN_SKILL_MIN_SESSIONS", "2"))
GLOBAL_SKILLS_DIR = Path(os.path.expanduser("~/.claude/skills"))


def _slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return (s or "memory")[:48]


def _cluster(memories: list[store.Memory], matrix: np.ndarray
             ) -> list[list[int]]:
    """Return clusters as lists of indices into the input lists."""
    n = len(memories)
    if n == 0 or matrix is None or matrix.shape[0] != n:
        return []

    # Sort indices by (use_count, confidence) descending — strongest seeds first.
    order = sorted(
        range(n),
        key=lambda i: (memories[i].use_count, memories[i].confidence),
        reverse=True,
    )

    used = [False] * n
    clusters: list[list[int]] = []
    for seed in order:
        if used[seed]:
            continue
        used[seed] = True
        members = [seed]
        seed_vec = matrix[seed]
        sims = matrix @ seed_vec
        for j in range(n):
            if used[j] or j == seed:
                continue
            if float(sims[j]) >= SIM_THRESHOLD:
                used[j] = True
                members.append(j)
        clusters.append(members)
    return clusters


def _scope_for(members: list[store.Memory]) -> tuple[str, Path]:
    """Return ('project'|'global', skills_dir)."""
    cwds = {m.source_cwd for m in members if m.source_cwd}
    if len(cwds) == 1:
        cwd = next(iter(cwds))
        return "project", Path(cwd) / ".claude" / "skills"
    return "global", GLOBAL_SKILLS_DIR


def _unique_dir(parent: Path, base_slug: str) -> Path:
    """Return parent/proposed-<slug> with -2, -3 suffix if it exists."""
    candidate = parent / f"proposed-{base_slug}"
    if not candidate.exists():
        return candidate
    i = 2
    while True:
        candidate = parent / f"proposed-{base_slug}-{i}"
        if not candidate.exists():
            return candidate
        i += 1


def _stub_skill(slug: str, members: list[store.Memory]) -> str:
    """Template SKILL.md when the Claude CLI is unavailable."""
    desc = members[0].summary.replace('"', "'")[:240]
    bullets = []
    for m in members:
        bullets.append(f"- **{m.title.strip()}** — {m.summary.strip()}")
    body = "\n".join(bullets)
    member_list = ", ".join(str(m.id) for m in members)
    return (
        "---\n"
        f"name: {slug}\n"
        f'description: "{desc}"\n'
        "---\n\n"
        f"# {slug}\n\n"
        "Recurring patterns distilled from prior sessions:\n\n"
        f"{body}\n\n"
        "<!-- generated by agentic-brain promote-skills; "
        f"members: [{member_list}] -->\n"
    )


def _claude_generate(slug: str, members: list[store.Memory]) -> str | None:
    """Ask the Claude CLI for a polished SKILL.md. None on any failure."""
    parts = []
    for m in members:
        parts.append(
            f"### memory {m.id} ({m.kind}, used {m.use_count}x, "
            f"confidence {m.confidence}/10)\n"
            f"title: {m.title}\nsummary: {m.summary}\ncontent: {m.content}"
        )
    catalog = "\n\n".join(parts)

    prompt = (
        "You are writing a Claude Code SKILL.md from a cluster of related "
        "memories the user has accumulated. Output ONLY the file contents, "
        "no fences, no commentary.\n\n"
        "Format:\n"
        "  - YAML frontmatter with `name: <slug>` and a one-sentence "
        "`description:` (<=200 chars, in double quotes).\n"
        "  - A short H1 matching the slug.\n"
        "  - 3-8 concrete bullet rules or patterns synthesised from the "
        "memories. Concrete > abstract; quote the user's own phrasing where "
        "it appears. No filler.\n\n"
        f"slug: {slug}\n\n"
        f"MEMORIES:\n{catalog}\n"
    )

    try:
        proc = subprocess.run(
            ["claude", "-p", prompt],
            capture_output=True, text=True, timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        _log.warning("claude CLI unavailable for skill %s: %s", slug, e)
        return None
    out = (proc.stdout or "").strip()
    if proc.returncode != 0 or not out.startswith("---"):
        _log.warning("claude returned non-skill output for %s (rc=%d)",
                     slug, proc.returncode)
        return None
    return out + "\n"


def _generate_skill_md(slug: str, members: list[store.Memory]) -> str:
    body = _claude_generate(slug, members)
    return body if body is not None else _stub_skill(slug, members)


def promote(dry_run: bool = False,
            min_cluster: int = DEFAULT_MIN_CLUSTER,
            min_sessions: int = DEFAULT_MIN_SESSIONS,
            loaded: tuple[list, np.ndarray | None] | None = None) -> dict:
    """Cluster promotable memories and write draft SKILL.md files.

    Pass `loaded` to reuse a (memories, matrix) snapshot already in hand.
    """
    all_mems, matrix = loaded if loaded is not None else store.load_all_for_scoring()
    eligible_idx = [
        i for i, m in enumerate(all_mems)
        if m.kind in PROMOTABLE_KINDS and m.promoted_to_skill is None
    ]
    if not eligible_idx or matrix is None:
        return {"promoted": 0, "skills": [], "dry_run": dry_run,
                "considered": len(eligible_idx)}

    eligible_mems = [all_mems[i] for i in eligible_idx]
    eligible_matrix = matrix[eligible_idx]

    clusters = _cluster(eligible_mems, eligible_matrix)

    written: list[dict] = []
    for cluster_indices in clusters:
        members = [eligible_mems[i] for i in cluster_indices]
        if len(members) < min_cluster:
            continue
        sessions = {m.source_session_id for m in members if m.source_session_id}
        if len(sessions) < min_sessions:
            continue

        seed = max(members, key=lambda m: (m.use_count, m.confidence))
        slug = _slugify(seed.title)
        scope, skills_dir = _scope_for(members)

        target_dir = _unique_dir(skills_dir, slug)
        skill_path = target_dir / "SKILL.md"

        record = {
            "slug": target_dir.name.removeprefix("proposed-"),
            "scope": scope,
            "path": str(skill_path),
            "member_ids": [m.id for m in members],
        }

        if not dry_run:
            target_dir.mkdir(parents=True, exist_ok=True)
            content = _generate_skill_md(record["slug"], members)
            skill_path.write_text(content)
            store.mark_promoted(record["member_ids"], record["slug"])
            _log.info("wrote skill %s (%d members) -> %s",
                      record["slug"], len(members), skill_path)
        written.append(record)

    return {
        "promoted": len(written),
        "skills": written,
        "dry_run": dry_run,
        "considered": len(eligible_mems),
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
