"""Export style/pattern memories to .github/copilot-instructions.md."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..store import list_memories

MAX_BYTES = 6000  # Copilot truncates aggressively past ~6KB
RELEVANT_KINDS = ("writing-style", "code-pattern", "preference")


def _format_section(title: str, items) -> str:
    if not items:
        return ""
    lines = [f"## {title}", ""]
    for m in items:
        lines.append(f"- **{m.title}** — {m.summary}")
        if m.content and len(m.content) < 400:
            lines.append(f"  - {m.content}")
    return "\n".join(lines)


def _gather(repo: str | None, limit: int = 50) -> list:
    cwd_prefix = repo if repo else None
    items = list_memories(limit=limit)
    if cwd_prefix:
        scoped = [m for m in items if m.source_cwd.startswith(cwd_prefix)]
        items = scoped or items  # fall back to global if nothing matches repo
    return [m for m in items if m.kind in RELEVANT_KINDS]


def export(out_path: str | None = None, repo: str | None = None) -> Path:
    repo_root = Path(repo) if repo else Path.cwd()
    target = Path(out_path) if out_path else repo_root / ".github" / "copilot-instructions.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    items = _gather(str(repo_root))
    by_kind: dict[str, list] = {k: [] for k in RELEVANT_KINDS}
    for m in items:
        by_kind[m.kind].append(m)

    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    header = (
        f"<!-- generated by agentic-brain at {ts}; "
        f"regenerate with: agentic-brain export-copilot -->\n"
        "# Project conventions\n\n"
        "These rules are distilled from prior sessions. Follow them unless the "
        "user explicitly overrides.\n\n"
    )
    body = "\n\n".join(filter(None, [
        _format_section("Writing style", by_kind["writing-style"]),
        _format_section("Code patterns", by_kind["code-pattern"]),
        _format_section("Preferences", by_kind["preference"]),
    ]))
    if not body:
        body = "_(no memories yet — run a few sessions, then re-export.)_"

    out = header + body + "\n"
    if len(out.encode("utf-8")) > MAX_BYTES:
        # keep the header and as much body as fits
        budget = MAX_BYTES - len(header.encode("utf-8")) - 8
        body_bytes = body.encode("utf-8")[:budget]
        out = header + body_bytes.decode("utf-8", errors="ignore") + "\n…\n"
    target.write_text(out, encoding="utf-8")
    return target
